elementos = {
        'Ac': {'numero_atomico': 89, 'nome': 'Actínio', 'massa': 227},
    'Al': {'numero_atomico': 13, 'nome': 'Alumínio', 'massa': 26.9815},
    'Am': {'numero_atomico': 95, 'nome': 'Amerício', 'massa': 243},
    'Sb': {'numero_atomico': 51, 'nome': 'Antimônio', 'massa': 121.75},
    'Ar': {'numero_atomico': 18, 'nome': 'Argônio', 'massa': 39.948},
    'As': {'numero_atomico': 33, 'nome': 'Arsênio', 'massa': 74.9216},
    'At': {'numero_atomico': 85, 'nome': 'Astato', 'massa': 210},
    'Ba': {'numero_atomico': 56, 'nome': 'Bário', 'massa': 137.34},
    'Bk': {'numero_atomico': 97, 'nome': 'Berquélio', 'massa': 247},
    'Be': {'numero_atomico': 4, 'nome': 'Berílio', 'massa': 9.0122},
    'Bi': {'numero_atomico': 83, 'nome': 'Bismuto', 'massa': 209},
    'Bh': {'numero_atomico': 107, 'nome': 'Bóhrio', 'massa': 262.1},
    'B': {'numero_atomico': 5, 'nome': 'Boro', 'massa': 10.811},
    'Br': {'numero_atomico': 35, 'nome': 'Bromo', 'massa': 79.909},
    'Cd': {'numero_atomico': 48, 'nome': 'Cádmio', 'massa': 112.4},
    'Ca': {'numero_atomico': 20, 'nome': 'Cálcio', 'massa': 40.08},
    'Cf': {'numero_atomico': 98, 'nome': 'Califórnio', 'massa': 251},
    'C': {'numero_atomico': 6, 'nome': 'Carbono', 'massa': 12.01115},
    'Ce': {'numero_atomico': 58, 'nome': 'Cério', 'massa': 140.12},
    'Cs': {'numero_atomico': 55, 'nome': 'Césio', 'massa': 132.905},
    'Pb': {'numero_atomico': 82, 'nome': 'Chumbo', 'massa': 207.19},
    'Cl': {'numero_atomico': 17, 'nome': 'Cloro', 'massa': 35.453},
    'Co': {'numero_atomico': 27, 'nome': 'Cobalto', 'massa': 58.93},
    'Cu': {'numero_atomico': 29, 'nome': 'Cobre', 'massa': 63.55},
    'Cn': {'numero_atomico': 112, 'nome': 'Copernício', 'massa': 285},
    'Kr': {'numero_atomico': 36, 'nome': 'Criptônio', 'massa': 83.8},
    'Cr': {'numero_atomico': 24, 'nome': 'Cromo', 'massa': 51.996},
    'Cm': {'numero_atomico': 96, 'nome': 'Cúrio', 'massa': 247},
    'Ds': {'numero_atomico': 110, 'nome': 'Darmstádio', 'massa': 269},
    'Dy': {'numero_atomico': 66, 'nome': 'Disprósio', 'massa': 162.5},
    'Db': {'numero_atomico': 105, 'nome': 'Dúbnio', 'massa': 262},
    'Es': {'numero_atomico': 99, 'nome': 'Einstênio', 'massa': 252},
    'S': {'numero_atomico': 16, 'nome': 'Enxofre', 'massa': 32.064},
    'Er': {'numero_atomico': 68, 'nome': 'Érbio', 'massa': 167.26},
    'Eu': {'numero_atomico': 63, 'nome': 'Európio', 'massa': 151.96},
    'Fm': {'numero_atomico': 100, 'nome': 'Férmio', 'massa': 257},
    'F': {'numero_atomico': 9, 'nome': 'Flúor', 'massa': 18.9984},
    'Fr': {'numero_atomico': 87, 'nome': 'Frâncio', 'massa': 223},
    'Gd': {'numero_atomico': 64, 'nome': 'Gadolínio', 'massa': 157.25},
    'Ga': {'numero_atomico': 31, 'nome': 'Gálio', 'massa': 69.723},
    'Ge': {'numero_atomico': 32, 'nome': 'Germânio', 'massa': 72.61},
    'Au': {'numero_atomico': 79, 'nome': 'Ouro', 'massa': 196.9665},
    'Hf': {'numero_atomico': 72, 'nome': 'Háfnio', 'massa': 178.49},
    'Hs': {'numero_atomico': 108, 'nome': 'Hássio', 'massa': 265},
    'He': {'numero_atomico': 2, 'nome': 'Hélio', 'massa': 4.0026},
    'Ho': {'numero_atomico': 67, 'nome': 'Hólmio', 'massa': 164.93},
    'H': {'numero_atomico': 1, 'nome': 'Hidrogênio', 'massa': 1.0079},
    'In': {'numero_atomico': 49, 'nome': 'Índio', 'massa': 114.82},
    'I': {'numero_atomico': 53, 'nome': 'Iodo', 'massa': 126.904},
    'Ir': {'numero_atomico': 77, 'nome': 'Irídio', 'massa': 192.22},
    'Fe': {'numero_atomico': 26, 'nome': 'Ferro', 'massa': 55.845},
    'Kr': {'numero_atomico': 36, 'nome': 'Criptônio', 'massa': 83.798},
    'La': {'numero_atomico': 57, 'nome': 'Lantânio', 'massa': 138.905},
    'Lr': {'numero_atomico': 103, 'nome': 'Laurêncio', 'massa': 266},
    'Pb': {'numero_atomico': 82, 'nome': 'Chumbo', 'massa': 207.2},
    'Li': {'numero_atomico': 3, 'nome': 'Lítio', 'massa': 6.941},
    'Lu': {'numero_atomico': 71, 'nome': 'Lutécio', 'massa': 174.97},
    'Mg': {'numero_atomico': 12, 'nome': 'Magnésio', 'massa': 24.305},
    'Mn': {'numero_atomico': 25, 'nome': 'Manganês', 'massa': 54.938},
    'Mt': {'numero_atomico': 109, 'nome': 'Meitnério', 'massa': 268},
    'Md': {'numero_atomico': 101, 'nome': 'Mendelévio', 'massa': 258},
    'Hg': {'numero_atomico': 80, 'nome': 'Mercúrio', 'massa': 200.59},
    'Mo': {'numero_atomico': 42, 'nome': 'Molibdênio', 'massa': 95.94},
    'Mc': {'numero_atomico': 115, 'nome': 'Moscóvio', 'massa': 288},
    'Nd': {'numero_atomico': 60, 'nome': 'Neodímio', 'massa': 144.24},
    'Ne': {'numero_atomico': 10, 'nome': 'Neônio', 'massa': 20.179},
    'Np': {'numero_atomico': 93, 'nome': 'Neptúnio', 'massa': 237},
    'Ni': {'numero_atomico': 28, 'nome': 'Níquel', 'massa': 58.693},
    'Nh': {'numero_atomico': 113, 'nome': 'Nihônio', 'massa': 284},
    'Nb': {'numero_atomico': 41, 'nome': 'Nióbio', 'massa': 92.906},
    'N': {'numero_atomico': 7, 'nome': 'Nitrogênio', 'massa': 14.007},
    'No': {'numero_atomico': 102, 'nome': 'Nobélio', 'massa': 259},
    'Os': {'numero_atomico': 76, 'nome': 'Ósmio', 'massa': 190.2},
    'O': {'numero_atomico': 8, 'nome': 'Oxigênio', 'massa': 15.999},
    'Pd': {'numero_atomico': 46, 'nome': 'Paládio', 'massa': 106.42},
    'Pa': {'numero_atomico': 91, 'nome': 'Protactínio', 'massa': 231.035},
    'Pm': {'numero_atomico': 61, 'nome': 'Promécio', 'massa': 145},
    'Pr': {'numero_atomico': 59, 'nome': 'Praseodímio', 'massa': 140.908},
    'Pu': {'numero_atomico': 94, 'nome': 'Plutônio', 'massa': 244},
    'Po': {'numero_atomico': 84, 'nome': 'Polônio', 'massa': 210},
    'K': {'numero_atomico': 19, 'nome': 'Potássio', 'massa': 39.098},
    'Pb': {'numero_atomico': 82, 'nome': 'Chumbo', 'massa': 207},
    'Pr': {'numero_atomico': 59, 'nome': 'Praseodímio', 'massa': 140.90765},
    'P': {'numero_atomico': 15, 'nome': 'Fósforo', 'massa': 30.97376},
    'Ra': {'numero_atomico': 88, 'nome': 'Rádio', 'massa': 226},
    'Rn': {'numero_atomico': 86, 'nome': 'Rádon', 'massa': 222},
    'Re': {'numero_atomico': 75, 'nome': 'Rênio', 'massa': 186.207},
    'Rh': {'numero_atomico': 45, 'nome': 'Ródio', 'massa': 102.905},
    'Rg': {'numero_atomico': 111, 'nome': 'Roentgênio', 'massa': 280},
    'Ru': {'numero_atomico': 44, 'nome': 'Rutênio', 'massa': 101.07},
    'Rb': {'numero_atomico': 37, 'nome': 'Rubídio', 'massa': 85.468},
    'Sm': {'numero_atomico': 62, 'nome': 'Samário', 'massa': 150.36},
    'Sc': {'numero_atomico': 21, 'nome': 'Escândio', 'massa': 44.956},
    'Sg': {'numero_atomico': 106, 'nome': 'Seabórgio', 'massa': 266},
    'Se': {'numero_atomico': 34, 'nome': 'Selênio', 'massa': 78.96},
    'Si': {'numero_atomico': 14, 'nome': 'Silício', 'massa': 28.085},
    'Ag': {'numero_atomico': 47, 'nome': 'Prata', 'massa': 107.868},
    'Na': {'numero_atomico': 11, 'nome': 'Sódio', 'massa': 22.99},
    'Sr': {'numero_atomico': 38, 'nome': 'Estrôncio', 'massa': 87.62},
    'S': {'numero_atomico': 16, 'nome': 'Enxofre', 'massa': 32.06},
    'Ta': {'numero_atomico': 73, 'nome': 'Tântalo', 'massa': 180.947},
    'Tc': {'numero_atomico': 43, 'nome': 'Tecnécio', 'massa': 98},
    'Te': {'numero_atomico': 52, 'nome': 'Telúrio', 'massa': 127.6},
    'Tb': {'numero_atomico': 65, 'nome': 'Térbio', 'massa': 158.925},
    'Tl': {'numero_atomico': 81, 'nome': 'Tálio', 'massa': 204.383},
    'Th': {'numero_atomico': 90, 'nome': 'Tório', 'massa': 232.038},
    'Tm': {'numero_atomico': 69, 'nome': 'Túlio', 'massa': 168.934},
    'Sn': {'numero_atomico': 50, 'nome': 'Estanho', 'massa': 118.71},
    'Ti': {'numero_atomico': 22, 'nome': 'Titânio', 'massa': 47.867},
    'W': {'numero_atomico': 74, 'nome': 'Tungstênio', 'massa': 183.84},
    'U': {'numero_atomico': 92, 'nome': 'Urânio', 'massa': 238.029},
    'V': {'numero_atomico': 23, 'nome': 'Vanádio', 'massa': 50.942},
    'Xe': {'numero_atomico': 54, 'nome': 'Xenônio', 'massa': 131.293},
    'Yb': {'numero_atomico': 70, 'nome': 'Itérbio', 'massa': 173.045},
    'Y': {'numero_atomico': 39, 'nome': 'Ítrio', 'massa': 88.906},
    'Zn': {'numero_atomico': 30, 'nome': 'Zinco', 'massa': 65.38},
    'Zr': {'numero_atomico': 40, 'nome': 'Zircônio', 'massa': 91.224}
}

def exibir_informacoes(sigla):
    if sigla in elementos:
        elemento = elementos[sigla]
        print(f"Elemento: {elemento['nome']}")
        print(f"Número Atômico: {elemento['numero_atomico']}")
        print(f"Massa: {elemento['massa']}")
    else:
        print("Elemento não encontrado.")

if __name__ == "__main__":
    while True:
        sigla = input("Digite a sigla do elemento químico (ou 'sair' para encerrar): ").capitalize()
        if sigla.lower() == 'sair':
            break
        exibir_informacoes(sigla)
